# Generated by Django 5.2.7 on 2026-02-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.CharField(choices=[('checkup', 'General Checkup (₱500)'), ('consultation', 'Specialist Consultation (₱800)'), ('surgery', 'Minor Surgery (₱1,500)'), ('therapy', 'Physical Therapy (₱1,200)')], default='checkup', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
