# Generated by Django 5.2.7 on 2026-02-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_service_type_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('completed', 'Completed'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
